import type { Metadata } from 'next';
import { Delius } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from './providers/ReactQueryProvider';

const delius = Delius({
  variable: '--font-Delius',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Meal Port',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${delius.variable} ${delius.variable} antialiased bg-[#EEE9DB]`}
      >
        <ReactQueryProvider>
          {children}
          <Toaster richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
